# EA1 – Carga y creación de dataset

Flujo: cargar el dataset Iris desde Hugging Face con `HFDatasetLoader`,
aplicar transformaciones al DataFrame y generar un resumen en `.txt`
con `DatasetSummarizer`.

In [2]:
from hf_loader import HFDatasetLoader
from dataset_summarizer import DatasetSummarizer

## 1. Carga del dataset

In [3]:
loader = HFDatasetLoader("scikit-learn/iris", split="train")
df = loader.load()

print("Dimensiones originales:", df.shape)
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Dimensiones originales: (150, 6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## 2. Transformaciones

Se aplican cuatro transformaciones al DataFrame original:
1. Eliminar la columna `Id`, que solo numera filas y no aporta información.
2. Renombrar las columnas a español.
3. Crear la columna `area_petalo` (largo × ancho del pétalo).
4. Filtrar las flores con largo de sépalo mayor a 5 cm.

In [4]:
df_t = df.drop(columns=["Id"])
df_t.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df_t = df_t.rename(columns={
    "SepalLengthCm": "largo_sepalo",
    "SepalWidthCm": "ancho_sepalo",
    "PetalLengthCm": "largo_petalo",
    "PetalWidthCm": "ancho_petalo",
    "Species": "especie",
})
df_t.head()

   largo_sepalo  ancho_sepalo  largo_petalo  ancho_petalo      especie
0           5.1           3.5           1.4           0.2  Iris-setosa
1           4.9           3.0           1.4           0.2  Iris-setosa
2           4.7           3.2           1.3           0.2  Iris-setosa
3           4.6           3.1           1.5           0.2  Iris-setosa
4           5.0           3.6           1.4           0.2  Iris-setosa

In [6]:
df_t["area_petalo"] = df_t["largo_petalo"] * df_t["ancho_petalo"]
df_t.head()

,largo_sepalo,ancho_sepalo,largo_petalo,ancho_petalo,especie,area_petalo
0,5.1,3.5,1.4,0.2,Iris-setosa,0.28
1,4.9,3.0,1.4,0.2,Iris-setosa,0.28
2,4.7,3.2,1.3,0.2,Iris-setosa,0.26
3,4.6,3.1,1.5,0.2,Iris-setosa,0.30
4,5.0,3.6,1.4,0.2,Iris-setosa,0.28

In [7]:
df_t = df_t[df_t["largo_sepalo"] > 5.0]
print("Dimensiones después del filtro:", df_t.shape)
df_t.head()

Dimensiones después del filtro: (118, 6)

,largo_sepalo,ancho_sepalo,largo_petalo,ancho_petalo,especie,area_petalo
0,5.1,3.5,1.4,0.2,Iris-setosa,0.28
5,5.4,3.9,1.7,0.4,Iris-setosa,0.68
10,5.4,3.7,1.5,0.2,Iris-setosa,0.30
14,5.8,4.0,1.2,0.2,Iris-setosa,0.24
15,5.7,4.4,1.5,0.4,Iris-setosa,0.60

In [8]:
print("Original:     ", df.shape, list(df.columns))
print("Transformado: ", df_t.shape, list(df_t.columns))

Original:      (150, 6) ['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
Transformado:  (118, 6) ['largo_sepalo', 'ancho_sepalo', 'largo_petalo', 'ancho_petalo', 'especie', 'area_petalo']

## 3. Resumen del DataFrame transformado

In [9]:
summarizer = DatasetSummarizer(df_t, "Iris transformado")
ruta = summarizer.save("resumen_iris.txt")

print(f"Resumen guardado en: {ruta}\n")
print(summarizer.build_summary())

Resumen guardado en: resumen_iris.txt

RESUMEN DEL DATASET: Iris transformado
Generado: 2026-10-25 15:56
============================================================

1. DIMENSIONES
Filas: 118
Columnas: 6

2. COLUMNAS Y TIPOS DE DATOS
largo_sepalo    float64
ancho_sepalo    float64
largo_petalo    float64
ancho_petalo    float64
especie             str
area_petalo     float64

3. VALORES NULOS POR COLUMNA
largo_sepalo    0
ancho_sepalo    0
largo_petalo    0
ancho_petalo    0
especie         0
area_petalo     0
Total de valores nulos: 0

4. ESTADÍSTICAS DESCRIPTIVAS (columnas numéricas)
       largo_sepalo  ancho_sepalo  largo_petalo  ancho_petalo  area_petalo
count        118.00        118.00        118.00        118.00       118.00
mean           6.13          3.05          4.32          1.43         7.14
std            0.69          0.45          1.53          0.67         4.37
min            5.10          2.20          1.20          0.10         0.15
25%            5.60          2.80          3.92          1.20         4.68
50%            6.10          3.00          4.70          1.50         6.75
75%            6.57          3.30          5.38          1.90        10.35
max            7.90          4.40          6.90          2.50        15.87

5. COLUMNAS CATEGÓRICAS (valores más frecuentes)
[especie] - 3 valores únicos
especie
Iris-virginica     49
Iris-versicolor    47
Iris-setosa        22

## Conclusión

Se cargó el dataset Iris (150 filas, 6 columnas) mediante `HFDatasetLoader`.
Se eliminó la columna `Id`, se renombraron las columnas a español, se creó
`area_petalo` y se filtraron las flores con sépalo mayor a 5 cm.
El resumen de `resumen_iris.txt` corresponde al DataFrame transformado.